name: pydata101
dependencies:
- python=3.5
- pandas=0.18
- seaborn=0.7
- bokeh=0.11
- scikit-learn=0.17
- pip=8.1
- jupyter=1.0
# Needed for pd.read_html
- lxml=3.6
- html5lib=0.999
- BeautifulSoup4=4.4
